---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cb-sgw 
  namespace: piptemplates
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cb-sgw
    spec:
      containers:
        - name: cb-sgw
          image: couchbase/sync-gateway:2.1.2-enterprise 
          args: ["/sync-gateway-config/sgw-config.json"] 
          volumeMounts: 
            - name: sgw-config-volume
              mountPath: /sync-gateway-config
              readOnly: true
          env:
            - name: GOMAXPROCS 
              value: "2"
          resources:
            requests:
              cpu: "1"
            limits:
              cpu: "1" 
      volumes: 
        - name: sgw-config-volume
          secret:
            secretName: cb-sgw-config
---
kind: Service
apiVersion: v1
metadata:
  name: cb-sgw
  namespace: piptemplates
spec:
  selector:
    app: cb-sgw
  type: NodePort
  ports:
  - protocol: TCP
    port: 4984 
    nodePort: 30984
