---
apiVersion: v1
kind: ReplicationController
metadata:
  namespace: piptemplates
  name: mosquitto-rc
spec:
  replicas: 1
  selector:
    app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
      - name: mosquitto-pod
        image: toke/mosquitto
        ports:
        - containerPort: 1883
        - containerPort: 9001
---
apiVersion: v1
kind: Service
metadata:
  namespace: piptemplates
  name: mqtt
  labels: 
    app: mosquitto
spec:
  type: NodePort
  ports:
  - name: port-1
    port: 1883
    nodePort: 31883
    protocol: TCP
  - name: port-2
    port: 9001
    nodePort: 31001
    protocol: TCP
  selector:
    app: mosquitto
