- hosts: master
  become: yes
  tasks:
    - name: initialize the cluster
      shell: kubeadm init --pod-network-cidr=<%=onprem_k8s_network%> --apiserver-advertise-address=<%=k8s_master_inet_addr%> >> cluster_initialized.txt
      args:
        chdir: $HOME
        creates: cluster_initialized.txt

    - name: create .kube directory
      become: yes
      become_user: <%=onprem_instance_username%>
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/<%=onprem_instance_username%>/.kube/config
        remote_src: yes
        owner: <%=onprem_instance_username%>

    - name: install Pod network
      become: yes
      become_user: <%=onprem_instance_username%>
      shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/v0.9.1/Documentation/kube-flannel.yml >> pod_network_setup.txt
      args:
        chdir: $HOME
        creates: pod_network_setup.txt
