- hosts: master
  become: yes
  tasks:
    - name: Delete directory for platform service yml files
      become: yes
      become_user: <%=onprem_instance_username%>
      file:
        path: $HOME/k8s_platform_services
        state: directory
        mode: 0755

    - name: Copy k8s deploy yml files
      become: yes
      become_user: <%=onprem_instance_username%>
      copy: src={{ item.src }} dest={{ item.dest }}
      with_items:
        - { src: '../templates/k8s_components/mosquitto.yml', dest: '$HOME/k8s_platform_services/mosquitto.yml' }
        - { src: '../templates/k8s_components/redis.yml', dest: '$HOME/k8s_platform_services/redis.yml' }

    - name: Delete nginx ingress components
      become: yes
      become_user: <%=onprem_instance_username%>
      raw: kubectl delete -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/mandatory.yaml

    - name: Delete ingress controller service
      become: yes
      become_user: <%=onprem_instance_username%>
      raw: kubectl delete -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/provider/cloud-generic.yaml

    - name: Delete mosquitto
      become: yes
      become_user: <%=onprem_instance_username%>
      raw: kubectl delete -f "$HOME/k8s_platform_services/mosquitto.yml"

    - name: Delete redis
      become: yes
      become_user: <%=onprem_instance_username%>
      raw: kubectl delete -f "$HOME/k8s_platform_services/redis.yml"
